(() => {
 'use strict';
 const list=document.getElementById('product-list'), template=list.querySelector('.product').cloneNode(true);
 const labels={main:'Основной каталог',unselected:'Не выбранные цвета',pattern:'Подклад с рисунком'};
 const toolbar=document.createElement('div');toolbar.className='editor-toolbar';toolbar.innerHTML='<button type="button" id="add-card">＋ Добавить карточку</button><p>Фото, названия и разделы сохраняются в этом браузере на вашем устройстве.</p><p id="editor-status" role="status"></p>';list.before(toolbar);
 const status=document.getElementById('editor-status');
 const dialog=document.createElement('dialog');dialog.className='card-editor';dialog.setAttribute('aria-labelledby','editor-title');dialog.innerHTML=`<form id="card-editor-form"><div class="editor-heading"><h2 id="editor-title">Карточка ткани</h2><button type="button" id="close-editor" aria-label="Закрыть">×</button></div><label>Название цвета / рисунка<input name="name" required maxlength="100"></label><label>Номер<input name="code" required maxlength="40" placeholder="Например, 70001"></label><label>Раздел<select name="collection"><option value="main">Основной каталог</option><option value="unselected">Не выбранные цвета</option><option value="pattern">Подклад с рисунком</option></select></label><label>Фото ткани<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="editor-help">Для новой карточки выберите фото. При редактировании фото можно оставить прежним.</p><img id="photo-preview" alt="Предпросмотр выбранного фото" hidden><p id="form-error" role="alert"></p><button type="submit" class="editor-save">Сохранить</button><button type="button" id="cancel-editor">Отмена</button></form>`;document.body.append(dialog);
 const form=dialog.querySelector('form'),error=document.getElementById('form-error'),preview=document.getElementById('photo-preview');let db,ready=false,active=null,busy=false,previewURL=null;const records=new Map();
 function changed(){document.dispatchEvent(new Event('catalogchanged'));}
 function button(card){if(card.querySelector('.edit-card'))return;const b=document.createElement('button');b.type='button';b.className='edit-card';b.textContent='Изменить / перенести';card.querySelector('.product-info').append(b);}
 function apply(record){
  let card=[...list.querySelectorAll('.product')].find(c=>c.dataset.colorCode===record.id);
  if(!card){if(!record.custom)return;card=template.cloneNode(true);card.querySelectorAll('[data-stock-bound]').forEach(e=>delete e.dataset.stockBound);const panel=card.querySelector('.inventory');panel.open=false;panel.dataset.expanded='false';panel.style.height='';card.querySelectorAll('input').forEach(i=>i.value='');card.querySelectorAll('.stock-status,.legacy-stock').forEach(e=>e.textContent='');card.querySelector('.stock-summary').textContent='Не указаны';card.dataset.colorCode=record.id;card.querySelector('form').dataset.code=record.id;list.append(card);}
  card.dataset.collection=record.collection;card.dataset.displayCode=record.code;card.dataset.displayName=record.name;card.dataset.search=record.name+' #'+record.code;const title=record.name+' #'+record.code;card.querySelector('h3').textContent=title;card.querySelector('.product-type').textContent=labels[record.collection];
  const photo=card.querySelector('.fabric');photo.setAttribute('aria-label','Образец ткани: '+title);
  if(record.photo){photo.style.backgroundImage=`url("${record.photo}")`;photo.style.backgroundSize='cover';photo.style.backgroundPosition='center';photo.classList.remove('fabric-pattern');}
  card.querySelector('caption').textContent='Остатки по граммажу, '+title;card.querySelectorAll('input').forEach(i=>i.setAttribute('aria-label',i.getAttribute('aria-label').replace(/цвет #[^,]+$/, 'цвет #'+record.code)));button(card);
 }
 list.querySelectorAll('.product').forEach(button);
 function close(){if(busy)return;dialog.close();if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null;}}
 function open(card){if(!ready){status.textContent='Хранилище ещё не готово или недоступно. Попробуйте снова.';return;}active=card;form.reset();error.textContent='';preview.hidden=true;const title=card?.querySelector('h3').textContent||'';form.elements.name.value=card?.dataset.displayName||title.replace(/ #[^#]+$/,'');form.elements.code.value=card?.dataset.displayCode||title.match(/ #([^#]+)$/)?.[1]||'';const mode=window.catalogView.getMode();form.elements.collection.value=card?.dataset.collection||(mode==='favorites'?'main':mode);form.elements.photo.required=!card;document.getElementById('editor-title').textContent=card?'Изменить карточку':'Добавить карточку';dialog.showModal();}
 document.getElementById('add-card').addEventListener('click',()=>open(null));list.addEventListener('click',e=>{const b=e.target.closest('.edit-card');if(b)open(b.closest('.product'));});document.getElementById('close-editor').onclick=close;document.getElementById('cancel-editor').onclick=close;dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 form.elements.photo.addEventListener('change',()=>{if(previewURL)URL.revokeObjectURL(previewURL);const file=form.elements.photo.files[0];preview.hidden=!file;if(file){previewURL=URL.createObjectURL(file);preview.src=previewURL;}});
 const readPhoto=file=>new Promise((resolve,reject)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type))return reject(Error('Выберите фото JPG, PNG или WebP.'));if(file.size>15*1024*1024)return reject(Error('Выберите фото размером до 15 МБ.'));const reader=new FileReader();reader.onerror=()=>reject(Error('Не удалось прочитать фото.'));reader.onload=()=>{const img=new Image();img.onload=()=>resolve(reader.result);img.onerror=()=>reject(Error('Файл не удалось открыть как изображение.'));img.src=reader.result;};reader.readAsDataURL(file);});
 form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;error.textContent='';const name=form.elements.name.value.trim(),code=form.elements.code.value.trim().replace(/^#+/,'');if(!name||!code){error.textContent='Укажите название и номер.';return;}busy=true;const save=form.querySelector('[type="submit"]');save.disabled=true;
  try {const id=active?.dataset.colorCode||'custom-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));const old=records.get(id);const record={...old,id,name,code,collection:form.elements.collection.value,custom:old?.custom||!active};const file=form.elements.photo.files[0];if(file)record.photo=await readPhoto(file);
   await new Promise((resolve,reject)=>{const tx=db.transaction('cards','readwrite');tx.objectStore('cards').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});records.set(id,record);apply(record);changed();window.catalogView.show(record.collection);status.textContent='Карточка сохранена на этом устройстве.';busy=false;close();
  }catch(err){error.textContent=err?.message||'Не удалось сохранить. Проверьте свободное место и разрешения браузера.';}finally{busy=false;save.disabled=false;}
 });
 try{const request=indexedDB.open('podklad-pro-catalog',1);request.onupgradeneeded=()=>request.result.createObjectStore('cards',{keyPath:'id'});request.onerror=()=>{status.textContent='Хранилище недоступно. Разрешите браузеру сохранять данные, чтобы редактировать карточки.';};request.onsuccess=()=>{db=request.result;const get=db.transaction('cards').objectStore('cards').getAll();get.onsuccess=()=>{get.result.forEach(r=>{if(typeof r.name==='string'&&typeof r.code==='string'&&labels[r.collection]){records.set(r.id,r);apply(r);}});ready=true;changed();};get.onerror=()=>{status.textContent='Не удалось загрузить сохранённые карточки.';};};}catch{status.textContent='Хранилище браузера недоступно.';}
})();
